### ISSUE TITLE
It is possible to enable branch protection rules at the organization level in GitHub

### ISSUE THREAD

**Issue by ollie-iterators** [w3c/validate-repos#125] opened 2023-06-17 17:31 UTC
I noticed that some of the issues with the repositories listed in this report is that some of the repositories don't have branch protection rules.

This could be fixed by adding branch protection rules at the organization level.

**Comment by dontcallmedom** [comment] 2023-06-28 09:45
cc @plehegar

**Comment by plehegar** [comment] 2023-06-29 21:57
According to https://stackoverflow.com/questions/54222881/enable-branch-protection-rules-in-github-at-the-organisation-level , this would require some code running on top of GitHub to manipulate the branch protection rules in all repositories. 

The rule in the report is preventive/ Looking at the [report](https://w3c.github.io/validate-repos/report.html?filter=unprotectedbranch), it doesn't look like the problem is widespread enough to warrant the development/maintenance of additional code. In addition, we're not aware of an actual problem that erupted because of lack of branch protection. 

So closing this one with no one but feel free to re-open if you disagree.

**Closed by plehegar** 2023-06-29 21:57 UTC
